/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LocationId = IDL.Nat;
export const Time = IDL.Int;
export const LocationEntry = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
  'locationLabel' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
      [LocationId],
      [],
    ),
  'deleteLocation' : IDL.Func([LocationId], [], []),
  'getLocationById' : IDL.Func([LocationId], [LocationEntry], ['query']),
  'getLocations' : IDL.Func([], [IDL.Vec(LocationEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LocationId = IDL.Nat;
  const Time = IDL.Int;
  const LocationEntry = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
    'locationLabel' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
        [LocationId],
        [],
      ),
    'deleteLocation' : IDL.Func([LocationId], [], []),
    'getLocationById' : IDL.Func([LocationId], [LocationEntry], ['query']),
    'getLocations' : IDL.Func([], [IDL.Vec(LocationEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };